{"name": "Авторизация курьера с невалидными логином - получено сообщение об ошибке", "status": "passed", "start": 1719935531286, "stop": 1719935531372, "uuid": "df30462e-46a3-4f1b-971e-bf738e15ee84", "historyId": "546c92096758c8040f10e6fb4313042a", "testCaseId": "546c92096758c8040f10e6fb4313042a", "fullName": "tests.test_courier.TestLoginCourier#test_authorization_invalid_login_authorization_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MacBook-Air-Vladislav.local"}, {"name": "thread", "value": "87558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}